---

- name: Provisioning docker containers
  hosts: JEN
  tasks:
   - name: start ubuntu docker container
     docker_container:
        image: james/ansible-ubuntu:jen
        name: "ubuntu{{item}}"
        state: started #started   #absent
        ports:
           - "330{{item}}:22"
           - "440{{item}}:80"  
     with_sequence: start=2 end=3

   - name: start centos docker container
     docker_container:
        image: james/ansible-centos:jen
        state: started #started #present  #absent
        name: "centos{{item}}"
        ports:
           - "220{{item}}:22"
           - "110{{item}}:80"  
     with_sequence: start=2 end=3


#yum install epel-release
#yum install python-pip
#pip install docker.py

#ansible-doc docker_container
